# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20180526_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Match',
        ),
    ]
