# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_match_winning_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='leaderboard.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='losing_score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='leaderboard.Player'),
        ),
    ]
