# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_auto_20180526_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
