# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='score',
            field=models.IntegerField(default=None),
        ),
    ]
