# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_ranking_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.Player'),
        ),
    ]
