# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_auto_20180602_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='PlayerRating',
        ),
    ]
