# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-12-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0014_auto_20180602_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.IntegerField(blank=True, default=1450, null=True),
        ),
    ]
