# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-12-12 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0017_auto_20231212_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='draw',
            field=models.BooleanField(default=False),
        ),
    ]
